#!/bin/bash
echo "in build hook"
env
echo "getting context path"
CONTEXTFOLDER=$(dirname $DOCKERFILE_PATH)
echo "starting buid"
docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
-f $DOCKERFILE_PATH -t $IMAGE_NAME $CONTEXTFOLDER