#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct. 
CONTEXTFOLDER=$(dirname $DOCKERFILE_PATH)
docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
-f $DOCKERFILE_PATH -t $IMAGE_NAME $CONTEXTFOLDER