#!/bin/bash
echo "in build hook"

VCS_REF=$(git rev-parse --short HEAD)
echo "VCS_REF=$VCS_REF"
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
echo "BUILD_DATE=$BUILD_DATE"

docker build --build-arg VCS_REF=$VCS_REF \
  --build-arg BUILD_DATE=$BUILD_DATE \
  -f ./Dockerfile -t $IMAGE_NAME .
